MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MyBlog/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
path("", views.home, name = "home"),
path("about/", views.about, name = "about"),
path("blog/", views.blog, name = "blog"),
]

MyBlog/home/models.py
from django.db import models

# Create your models here.

class Blogs(models.Model):
	subject = models.CharField(max_length=200)
	category = models.CharField(max_length=200)
	datetime = models.DateTimeField()
	
	def __str__(self):
		return self.subject

class BlogData(models.Model):
	blogs = models.ForeignKey(Blogs, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	content = models.TextField()
	image = models.ImageField(upload_to='images/', blank=True, null=True)

	def __str__(self):
		return self.title

MyBlog/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Blogs, BlogData
# Create your views here.

def home(response):
	bg = Blogs.objects.all()
	return render(response, "home/home.html", {"blog":bg})


def about(response):
	return render(response, "home/about.html", {})

def blog(response):
	return render(response, "home/blog.html", {})

MyBlog/home/templates/home/about.html
{% extends 'home/base.html' %}

MyBlog/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	
	<meta charset="utf-8">
	<title>Information train</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
</head>
<body>
	<div class="main">
	<div class="navbar">
		<ul>
			<li class="menu"><a href="{% url 'home' %}">Home</a></li>
			<li class="menu"><a href="{% url 'about' %}">About Us</a></li>
		</ul>
	</div>
	<div class="left" style="float: left;">
		{% block left %}
		{% endblock %}
	</div>
	<div class="right" style="float: right;">
		{% block right %}
		{% endblock %}
	</div>
	<div class="content">
		{% block content %}
		{% endblock %}
	</div>
	</div>	
</body>
</html>

MyBlog/home/templates/home/blog.html
{% extends 'home/base.html' %}

{% block content %}
	<div>
		<h1>BLOG</h1>
	</div>	
{% endblock %}

MyBlog/home/templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}
	{% for bg in blog %}
	<a href="{% url 'blog' %}">
	<div class="item">
		{% for bgdt in bg.blogdata_set.all %}
		    <img src="{{bgdt.image.url}}">
		    <h2>{{bgdt.title}}</h2>
		    <h4>{{bg.subject}}</h4>
			<h5>{{bg.category}} {{bg.datetime}}</h5>
		{% endfor %}
	</div>
	</a>
	{% endfor %}
{% endblock %}

{% block left %}
<p>Left Sidejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjdklasnfljanflajjdklkajk;ajk;lajf;kadjfk;adfj;kaj</p>
{% endblock %}

{% block right %}
<p>Right SidejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjFLJABFKJSBFJSBFSJBFSJLFBSJLFBLSJFBLSJFBSLJF</p>
{% endblock %}